import React, { useState, useEffect, useCallback } from 'react';
import { TrendingUp, Clock, AlertCircle, MapPin, RefreshCw } from 'lucide-react';
import type { ZoneForecast, ForecastStatus } from '../../types/forecast';
import { getZoneForecast } from '../../services/forecastService';
import { PUNE_MOCK_ZONES } from '../../data/puneZones';
import { CurrentPm25Panel } from './CurrentPm25Panel';
import { ActualVsPredictedChart } from './ActualVsPredictedChart';
import './ForecastSection.css';

interface ForecastSectionProps {
  selectedZoneId?: string | null;
  onSelectZone?: (zoneId: string) => void;
  /** Optional override for testing/QA purposes without hitting network */
  overrideData?: ZoneForecast | null;
}

export const ForecastSection: React.FC<ForecastSectionProps> = ({
  selectedZoneId = null,
  onSelectZone,
  overrideData,
}) => {
  const [fetchedData, setFetchedData] = useState<ZoneForecast | null>(null);
  const [fetchError, setFetchError] = useState<boolean>(false);
  const [retryNonce, setRetryNonce] = useState<number>(0);

  // Resolve human-readable name from mock zones
  const activeZoneFeature = PUNE_MOCK_ZONES.features.find(
    (f) => f.properties.id === selectedZoneId
  );
  const zoneDisplayName = activeZoneFeature
    ? activeZoneFeature.properties.name
    : (selectedZoneId ?? 'Selected Zone');

  const isOverridden = overrideData !== undefined;
  const forecastData = isOverridden ? overrideData : fetchedData;

  // Purely derived status to eliminate cascading renders
  let status: ForecastStatus;
  if (isOverridden) {
    if (!overrideData) {
      status = selectedZoneId ? 'empty' : 'idle';
    } else if (!overrideData.forecast || overrideData.forecast.length === 0) {
      status = 'empty';
    } else {
      status = 'success';
    }
  } else if (!selectedZoneId) {
    status = 'idle';
  } else if (fetchError) {
    status = 'error';
  } else if (!fetchedData || fetchedData.zoneId !== selectedZoneId) {
    status = 'loading';
  } else if (!fetchedData.forecast || fetchedData.forecast.length === 0) {
    status = 'empty';
  } else {
    status = 'success';
  }

  const fetchForecast = useCallback((zoneId: string, signal?: AbortSignal) => {
    getZoneForecast(zoneId, signal)
      .then((data) => {
        setFetchedData(data);
        setFetchError(false);
      })
      .catch((err: unknown) => {
        if (err instanceof DOMException && err.name === 'AbortError') {
          return;
        }
        // Fails gracefully when backend is not available yet
        setFetchedData(null);
        setFetchError(true);
      });
  }, []);

  useEffect(() => {
    if (isOverridden || !selectedZoneId) {
      return;
    }

    const controller = new AbortController();
    fetchForecast(selectedZoneId, controller.signal);

    return () => {
      controller.abort();
    };
  }, [selectedZoneId, isOverridden, fetchForecast, retryNonce]);

  const handleRetry = () => {
    setFetchError(false);
    setFetchedData(null);
    setRetryNonce((prev) => prev + 1);
  };

  return (
    <div className="forecast-card-container">
      {/* Header bar */}
      <div className="forecast-card-header">
        <div className="forecast-header-main">
          <div className="forecast-header-icon">
            <TrendingUp size={20} />
          </div>
          <div>
            <h3 className="forecast-title">24-Hour PM2.5 Forecast</h3>
            <p className="forecast-subtitle">
              {selectedZoneId
                ? `${zoneDisplayName} • Observed Telemetry & Modeled Projections`
                : 'Pune Urban Region • Select a zone to view forecast'}
            </p>
          </div>
        </div>

        {selectedZoneId && (
          <div className="forecast-header-meta">
            <span className="modeled-badge-dashed" title="Projection generated by ML model">
              <span className="dot-dashed" />
              <span>MODELED 24H</span>
            </span>
          </div>
        )}
      </div>

      {/* Zone quick-selection bar */}
      <div className="forecast-zone-switcher">
        <span className="switcher-label">Zone:</span>
        {PUNE_MOCK_ZONES.features.map((feature) => {
          const isSelected = selectedZoneId === feature.properties.id;
          return (
            <button
              key={feature.properties.id}
              type="button"
              className={`zone-chip ${isSelected ? 'active' : ''}`}
              onClick={() => onSelectZone?.(feature.properties.id)}
            >
              {feature.properties.name}
            </button>
          );
        })}
      </div>

      {/* UX STATE A: Initial / No zone selected */}
      {status === 'idle' && (
        <div className="state-initial-card">
          <div className="state-initial-icon-wrap">
            <MapPin size={22} />
          </div>
          <h4 className="state-initial-title">Select a zone to view environmental data.</h4>
          <p className="state-initial-desc">
            Click any of the 6 Pune test zones on the map or use the zone buttons above to view real-time PM2.5 observations and 24-hour predictive modeling.
          </p>
          <div className="initial-zones-prompt">
            {PUNE_MOCK_ZONES.features.slice(0, 3).map((f) => (
              <button
                key={f.properties.id}
                type="button"
                className="zone-chip"
                onClick={() => onSelectZone?.(f.properties.id)}
              >
                Inspect {f.properties.name}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* UX STATE B: Loading State / Skeleton */}
      {status === 'loading' && (
        <div className="state-loading-card">
          <div className="loading-indicator-row">
            <div className="loading-spinner" />
            <span>Loading forecast data for {zoneDisplayName}...</span>
          </div>
          <div className="skeleton-pulse skeleton-box" />
          <div className="skeleton-pulse skeleton-chart" />
        </div>
      )}

      {/* UX STATE D: Error State */}
      {status === 'error' && (
        <div className="state-error-card">
          <div className="error-icon-wrap">
            <AlertCircle size={22} />
          </div>
          <h4 className="error-title">Forecast data could not be loaded.</h4>
          <p className="error-subtitle">
            The environmental forecast endpoint for {zoneDisplayName} is currently offline or unreachable. Please verify backend service connection.
          </p>
          <button type="button" className="error-retry-btn" onClick={handleRetry}>
            <RefreshCw size={13} />
            <span>Retry Connection</span>
          </button>
        </div>
      )}

      {/* UX STATE E: Empty State (When zone has no forecast points) */}
      {status === 'empty' && (
        <div className="forecast-content-grid">
          <CurrentPm25Panel
            zoneName={zoneDisplayName}
            currentPm25={forecastData?.currentPm25 ?? null}
            unit={forecastData?.unit}
            lastUpdated={forecastData?.lastUpdated}
          />
          <div className="forecast-chart-card">
            <div className="chart-card-header">
              <h4 className="chart-card-title">Actual vs Predicted PM2.5</h4>
              <span className="chart-horizon-badge">
                <Clock size={12} />
                <span>Next 24 Hours</span>
              </span>
            </div>
            <ActualVsPredictedChart forecast={[]} unit={forecastData?.unit} />
          </div>
        </div>
      )}

      {/* UX STATE C: Success State */}
      {status === 'success' && forecastData && (
        <div className="forecast-content-grid">
          <CurrentPm25Panel
            zoneName={forecastData.zoneName || zoneDisplayName}
            currentPm25={forecastData.currentPm25}
            unit={forecastData.unit}
            lastUpdated={forecastData.lastUpdated}
          />

          <div className="forecast-chart-card">
            <div className="chart-card-header">
              <h4 className="chart-card-title">Actual vs Predicted PM2.5</h4>
              <span className="chart-horizon-badge">
                <Clock size={12} />
                <span>Next 24 Hours</span>
              </span>
            </div>

            <ActualVsPredictedChart
              forecast={forecastData.forecast}
              unit={forecastData.unit}
            />
          </div>
        </div>
      )}
    </div>
  );
};
